secrets:
- AIRTABLE_API_KEY
- AIRTABLE_BASE_ID
- AIRTABLE_TREES_TABLE_NAME
- AIRTABLE_SPECIES_TABLE_NAME
- AIRTABLE_SUPERVISORS_TABLE_NAME
- AIRTABLE_SITES_TABLE_NAME
- CLOUDINARY_CLOUD_NAME
- CLOUDINARY_UPLOAD_PRESET_NAME
outputs:
- ./Tree Tracker/Secrets.swift